export abstract class JwtTokenError {
  static readonly ERR_TOKEN_EXPIRED = 'ERR_TOKEN_EXPIRED';
  static readonly ERR_TOKEN_INVALID = 'ERR_TOKEN_INVALID';
  static readonly ERR_TOKEN_UNAUTHORIZED = 'ERR_TOKEN_UNAUTHORIZED';

  static readonly ERR_SIGNATURE_TOKEN_EXPIRED = 'ERR_SIGNATURE_TOKEN_EXPIRED';
  static readonly ERR_SIGNATURE_TOKEN_INVALID = 'ERR_SIGNATURE_TOKEN_INVALID';
  static readonly ERR_SIGNATURE_TOKEN_UNAUTHORIZED =
    'ERR_SIGNATURE_TOKEN_UNAUTHORIZED';
}
