export abstract class AuthSuccessMessage {
	static readonly SUCCESS_AUTH_SIGN_IN = "SUCCESS_AUTH_SIGN_IN";
	static readonly SUCCESS_AUTH_CHECK_EMAIL = "SUCCESS_AUTH_CHECK_EMAIL";
	static readonly SUCCESS_AUTH_REFRESH_TOKEN = "SUCCESS_AUTH_REFRESH_TOKEN";
	static readonly SUCCESS_AUTH_SIGN_OUT = "SUCCESS_AUTH_SIGN_OUT";
	static readonly SUCCESS_RESET_PASSWORD = "SUCCESS_RESET_PASSWORD";
	static readonly SUCCESS_AUTH_SIGN_IN_WITH_GOOGLE =
		"SUCCESS_AUTH_SIGN_IN_WITH_GOOGLE";
	static readonly SUCCESS_AUTH_SIGN_UP_WITH_GOOGLE =
		"SUCCESS_AUTH_SIGN_UP_WITH_GOOGLE";
	static readonly SUCCESS_AUTH_SIGN_UP_CACHED = "SUCCESS_AUTH_SIGN_UP_CACHED";
	static readonly SUCCESS_AUTH_SIGN_UP = "SUCCESS_AUTH_SIGN_UP";
}
