export abstract class ConsultationSuccessMessage {
	static readonly SUCCESS_GET_CONSULTATION = "SUCCESS_GET_CONSULTATION";
	static readonly SUCCESS_CHECK_ORDER_SCHEDULE_OVERLAPS =
		"SUCCESS_CHECK_ORDER_SCHEDULE_OVERLAPS";
	static readonly SUCCESS_CREATE_CONSULTATION_ORDER =
		"SUCCESS_CREATE_CONSULTATION_ORDER";
	static readonly SUCCESS_UPDATE_CONSULTATION_AS_SCHEDULED =
		"SUCCESS_UPDATE_CONSULTATION_AS_SCHEDULED";
	static readonly SUCCESS_UPDATE_CONSULTATION_AS_FINISHED =
		"SUCCESS_UPDATE_CONSULTATION_AS_FINISHED";
	static readonly SUCCESS_UPDATE_CONSULTATION_AS_RE_SCHEDULED =
		"SUCCESS_UPDATE_CONSULTATION_AS_RE_SCHEDULED";
	static readonly SUCCESS_UPDATE_CONSULTATION_AS_CANCELLED =
		"SUCCESS_UPDATE_CONSULTATION_AS_CANCELLED";
}
