export abstract class MedicalRecordSuccessMessage {
	static readonly SUCCESS_GET_MEDICAL_RECORD_KEY =
		"SUCCESS_GET_MEDICAL_RECORD_KEY";
	static readonly SUCCESS_CREATE_MEDICAL_RECORD_KEY =
		"SUCCESS_CREATE_MEDICAL_RECORD_KEY";

	static readonly SUCCESS_GET_MEDICAL_RECORD = "SUCCESS_GET_MEDICAL_RECORD";

	static readonly SUCCESS_BIND_PATIENT = "SUCCESS_BIND_PATIENT";
	static readonly SUCCESS_UNBIND_PATIENT = "SUCCESS_UNBIND_PATIENT";
}
