export abstract class NutritionistSuccessMessage {
	static readonly SUCCESS_GET_NUTRITIONIST = "SUCCESS_GET_NUTRITIONIST";

	static readonly SUCCESS_GET_CONSULTATION_META =
		"SUCCESS_GET_CONSULTATION_META";

	static readonly SUCCESS_GET_CREDENTIAL = "SUCCESS_GET_CREDENTIAL";
	static readonly SUCCESS_UPDATE_CREDENTIAL = "SUCCESS_UPDATE_CREDENTIAL";

	static readonly SUCCESS_GET_DASHBOARD = "SUCCESS_GET_DASHBOARD";
	static readonly SUCCESS_GET_DASHBOARD_META = "SUCCESS_GET_DASHBOARD_META";

	static readonly SUCCESS_GET_OCCUPATION = "SUCCESS_GET_OCCUPATION";
	static readonly SUCCESS_UPDATE_OCCUPATION = "SUCCESS_UPDATE_OCCUPATION";

	static readonly SUCCESS_GET_PRICE = "SUCCESS_GET_PRICE";
	static readonly SUCCESS_UPDATE_PRICE = "SUCCESS_UPDATE_PRICE";

	static readonly SUCCESS_GET_REGISTRATION_CERTIFICATE =
		"SUCCESS_GET_REGISTRATION_CERTIFICATE";
	static readonly SUCCESS_UPDATE_REGISTRATION_CERTIFICATE =
		"SUCCESS_UPDATE_REGISTRATION_CERTIFICATE";
	static readonly SUCCESS_CREATE_REGISTRATION_CERTIFICATE =
		"SUCCESS_CREATE_REGISTRATION_CERTIFICATE";
	static readonly SUCCESS_DELETE_REGISTRATION_CERTIFICATE =
		"SUCCESS_DELETE_REGISTRATION_CERTIFICATE";

	static readonly SUCCESS_GET_SCHEDULE = "SUCCESS_GET_SCHEDULE";
	static readonly SUCCESS_TOGGLE_SCHEDULE_ACTIVE =
		"SUCCESS_TOGGLE_SCHEDULE_ACTIVE";
	static readonly SUCCESS_GET_SCHEDULE_TIME = "SUCCESS_GET_SCHEDULE_TIME";
	static readonly SUCCESS_CREATE_SCHEDULE_TIME = "SUCCESS_CREATE_SCHEDULE_TIME";
	static readonly SUCCESS_UPDATE_SCHEDULE_TIME = "SUCCESS_UPDATE_SCHEDULE_TIME";
	static readonly SUCCESS_DELETE_SCHEDULE_TIME = "SUCCESS_DELETE_SCHEDULE_TIME";

	static readonly SUCCESS_GET_NUTRITIONIST_SYSTEM_SETTING =
		"SUCCESS_GET_NUTRITIONIST_SYSTEM_SETTING";
	static readonly SUCCESS_UPDATE_NUTRITIONIST_SYSTEM_SETTING =
		"SUCCESS_UPDATE_NUTRITIONIST_SYSTEM_SETTING";
}
