export abstract class RegistrationCertificateSuccessMessage {
	static readonly SUCCESS_GET_REGISTRATION_CERTIFICATE =
		"SUCCESS_GET_REGISTRATION_CERTIFICATE";
	static readonly SUCCESS_UPDATE_REGISTRATION_CERTIFICATE =
		"SUCCESS_UPDATE_REGISTRATION_CERTIFICATE";
	static readonly SUCCESS_CREATE_REGISTRATION_CERTIFICATE =
		"SUCCESS_CREATE_REGISTRATION_CERTIFICATE";
	static readonly SUCCESS_DELETE_REGISTRATION_CERTIFICATE =
		"SUCCESS_DELETE_REGISTRATION_CERTIFICATE";
}
