export abstract class AccountValidationMessage {
	static readonly ERR_EMAIL_REQUIRED = "ERR_EMAIL_REQUIRED";
	static readonly ERR_EMAIL_INVALID = "ERR_EMAIL_INVALID";
	static readonly ERR_EMAIL_MUST_BE_STRING = "ERR_EMAIL_MUST_BE_STRING";

	static readonly ERR_PASSWORD_REQUIRED = "ERR_PASSWORD_REQUIRED";
	static readonly ERR_PASSWORD_MUST_BE_STRING = "ERR_PASSWORD_MUST_BE_STRING";
	static readonly ERR_PASSWORD_MIN_LENGTH = "ERR_PASSWORD_MIN_LENGTH";
	static readonly ERR_PASSWORD_MAX_LENGTH = "ERR_PASSWORD_MAX_LENGTH";
	static readonly ERR_PASSWORD_PATTERN = "ERR_PASSWORD_PATTERN";

	static readonly ERR_CONFIRM_PASSWORD_REQUIRED =
		"ERR_CONFIRM_PASSWORD_REQUIRED";
	static readonly ERR_CONFIRM_PASSWORD_MUST_BE_STRING =
		"ERR_CONFIRM_PASSWORD_MUST_BE_STRING";
	static readonly ERR_CONFIRM_PASSWORD_MIN_LENGTH =
		"ERR_CONFIRM_PASSWORD_MIN_LENGTH";
	static readonly ERR_CONFIRM_PASSWORD_MAX_LENGTH =
		"ERR_CONFIRM_PASSWORD_MAX_LENGTH";
	static readonly ERR_CONFIRM_PASSWORD_PATTERN = "ERR_CONFIRM_PASSWORD_PATTERN";
	static readonly ERR_CONFIRM_PASSWORD_NOT_MATCH =
		"ERR_CONFIRM_PASSWORD_NOT_MATCH";

	static readonly ERR_FCM_TOKEN_REQUIRED = "ERR_FCM_TOKEN_REQUIRED";
	static readonly ERR_FCM_TOKEN_MUST_BE_STRING = "ERR_FCM_TOKEN_MUST_BE_STRING";

	static readonly ERR_SIGNATURE_REQUIRED = "ERR_SIGNATURE_REQUIRED";
	static readonly ERR_SIGNATURE_MUST_BE_STRING = "ERR_SIGNATURE_MUST_BE_STRING";

	static readonly ERR_OTP_REQUIRED = "ERR_OTP_REQUIRED";
	static readonly ERR_OTP_MUST_BE_STRING = "ERR_OTP_MUST_BE_STRING";

	static readonly ERR_GOOGLE_JWT_TOKEN_REQUIRED =
		"ERR_GOOGLE_JWT_TOKEN_REQUIRED";
	static readonly ERR_GOOGLE_JWT_TOKEN_INVALID = "ERR_GOOGLE_JWT_TOKEN_INVALID";
	static readonly ERR_GOOGLE_JWT_TOKEN_MUST_BE_STRING =
		"ERR_GOOGLE_JWT_TOKEN_MUST_BE_STRING";
	static readonly ERR_GOOGLE_JWT_TOKEN_MUST_BE_JWT =
		"ERR_GOOGLE_JWT_TOKEN_MUST_BE_JWT";
}
