export abstract class ConsultationValidationMessage {
	static readonly ERR_DURATION_REQUIRED = "ERR_DURATION_REQUIRED";
	static readonly ERR_DURATION_MUST_BE_NUMBER = "ERR_DURATION_MUST_BE_NUMBER";

	static readonly ERR_PATIENT_NOTE_REQUIRED = "ERR_PATIENT_NOTE_REQUIRED";
	static readonly ERR_PATIENT_NOTE_MUST_BE_STRING =
		"ERR_PATIENT_NOTE_MUST_BE_STRING";

	static readonly ERR_NUTRITIONIST_NOTE_REQUIRED =
		"ERR_NUTRITIONIST_NOTE_REQUIRED";
	static readonly ERR_NUTRITIONIST_NOTE_MUST_BE_STRING =
		"ERR_NUTRITIONIST_NOTE_MUST_BE_STRING";

	static readonly ERR_CONSULTATION_TYPE_REQUIRED =
		"ERR_CONSULTATION_TYPE_REQUIRED";
	static readonly ERR_CONSULTATION_TYPE_MUST_BE_ENUM =
		"ERR_CONSULTATION_TYPE_MUST_BE_ENUM";
	static readonly ERR_CONSULTATION_TYPE_INVALID =
		"ERR_CONSULTATION_TYPE_INVALID";

	static readonly ERR_CONSULTATION_STATUS_REQUIRED =
		"ERR_CONSULTATION_STATUS_REQUIRED";
	static readonly ERR_CONSULTATION_STATUS_MUST_BE_ENUM =
		"ERR_CONSULTATION_STATUS_MUST_BE_ENUM";
	static readonly ERR_CONSULTATION_STATUS_INVALID =
		"ERR_CONSULTATION_STATUS_INVALID";

	static readonly ERR_PAYMENT_SOURCE_REQUIRED = "ERR_PAYMENT_SOURCE_REQUIRED";
	static readonly ERR_PAYMENT_SOURCE_MUST_BE_ENUM =
		"ERR_PAYMENT_SOURCE_MUST_BE_ENUM";
	static readonly ERR_PAYMENT_SOURCE_INVALID = "ERR_PAYMENT_SOURCE_INVALID";
}
