export abstract class GoogleJwtTokenValidationMessage {
	static readonly ERR_GOOGLE_JWT_TOKEN_REQUIRED =
		"ERR_GOOGLE_JWT_TOKEN_REQUIRED";
	static readonly ERR_GOOGLE_JWT_TOKEN_INVALID = "ERR_GOOGLE_JWT_TOKEN_INVALID";
	static readonly ERR_GOOGLE_JWT_TOKEN_MUST_BE_STRING =
		"ERR_GOOGLE_JWT_TOKEN_MUST_BE_STRING";
}
