export class MedicalRecordValidationMessage {
	static readonly ERR_MEDICAL_RECORD_KEY_ID_REQUIRED =
		"ERR_MEDICAL_RECORD_KEY_ID_REQUIRED";

	static readonly ERR_HEIGHT_REQUIRED = "ERR_HEIGHT_REQUIRED";
	static readonly ERR_HEIGHT_MUST_BE_NUMBER = "ERR_HEIGHT_MUST_BE_NUMBER";
	static readonly ERR_HEIGHT_MIN_100 = "ERR_HEIGHT_MIN_100";
	static readonly ERR_HEIGHT_MAX_300 = "ERR_HEIGHT_MAX_300";

	static readonly ERR_WEIGHT_REQUIRED = "ERR_WEIGHT_REQUIRED";
	static readonly ERR_WEIGHT_MUST_BE_NUMBER = "ERR_WEIGHT_MUST_BE_NUMBER";
	static readonly ERR_WEIGHT_MIN_30 = "ERR_WEIGHT_MIN_30";
	static readonly ERR_WEIGHT_MAX_150 = "ERR_WEIGHT_MAX_150";

	static readonly ERR_DAILY_CALORIES_REQUIRED = "ERR_DAILY_CALORIES_REQUIRED";
	static readonly ERR_DAILY_CALORIES_MUST_BE_NUMBER =
		"ERR_DAILY_CALORIES_MUST_BE_NUMBER";
	static readonly ERR_DAILY_CALORIES_MIN_800 = "ERR_DAILY_CALORIES_MIN_800";
	static readonly ERR_DAILY_CALORIES_MAX_10000 = "ERR_DAILY_CALORIES_MAX_10000";

	static readonly ERR_ACTIVITY_LEVEL_REQUIRED = "ERR_ACTIVITY_LEVEL_REQUIRED";
	static readonly ERR_ACTIVITY_LEVEL_INVALID = "ERR_ACTIVITY_LEVEL_INVALID";
	static readonly ERR_ACTIVITY_LEVEL_MUST_BE_ENUM =
		"ERR_ACTIVITY_LEVEL_MUST_BE_ENUM";
}
