export class PhoneNumberValidationMessage {
	static readonly PHONE_NUMBER_MUST_BE_A_STRING =
		"PHONE_NUMBER_MUST_BE_A_STRING";
	static readonly PHONE_NUMBER_MUST_NOT_BE_EMPTY =
		"PHONE_NUMBER_MUST_NOT_BE_EMPTY";
	static readonly PHONE_NUMBER_MUST_BE_A_VALID_PHONE_NUMBER =
		"PHONE_NUMBER_MUST_BE_A_VALID_PHONE_NUMBER";
}
