export abstract class PriceValidationMessage {
	static readonly ERR_ONLINE_PRICE_REQUIRED = "ERR_ONLINE_PRICE_REQUIRED";
	static readonly ERR_ONLINE_PRICE_INVALID = "ERR_ONLINE_PRICE_INVALID";
	static readonly ERR_ONLINE_PRICE_MUST_BE_NUMBER =
		"ERR_ONLINE_PRICE_MUST_BE_NUMBER";
	static readonly ERR_ONLINE_PRICE_MIN = "ERR_ONLINE_PRICE_MIN_50000";
	static readonly ERR_ONLINE_PRICE_MAX = "ERR_ONLINE_PRICE_MAX_10000000";

	static readonly ERR_OFFLINE_PRICE_REQUIRED = "ERR_OFFLINE_PRICE_REQUIRED";

	static readonly ERR_OFFLINE_PRICE_INVALID = "ERR_OFFLINE_PRICE_INVALID";
	static readonly ERR_OFFLINE_PRICE_MUST_BE_NUMBER =
		"ERR_OFFLINE_PRICE_MUST_BE_NUMBER";
	static readonly ERR_OFFLINE_PRICE_MIN = "ERR_OFFLINE_PRICE_MIN_50000";
	static readonly ERR_OFFLINE_PRICE_MAX = "ERR_OFFLINE_PRICE_MAX_10000000";
}
