export abstract class ProfileValidationMessage {
	static readonly ERR_NAME_MUST_BE_STRING = "ERR_NAME_MUST_BE_STRING";
	static readonly ERR_NAME_REQUIRED = "ERR_NAME_REQUIRED";

	static readonly ERR_GENDER_REQUIRED = "ERR_GENDER_REQUIRED";
	static readonly ERR_GENDER_INVALID = "ERR_GENDER_INVALID";

	static readonly ERR_PHONE_NUMBER_MUST_BE_STRING =
		"ERR_PHONE_NUMBER_MUST_BE_STRING";
	static readonly ERR_PHONE_NUMBER_REQUIRED = "ERR_PHONE_NUMBER_REQUIRED";
	static readonly ERR_PHONE_NUMBER_INVALID = "ERR_PHONE_NUMBER_INVALID";

	static readonly ERR_PLACE_OF_BIRTH_MUST_BE_STRING =
		"ERR_PLACE_OF_BIRTH_MUST_BE_STRING";
	static readonly ERR_PLACE_OF_BIRTH_REQUIRED = "ERR_PLACE_OF_BIRTH_REQUIRED";

	static readonly ERR_DATE_OF_BIRTH_MUST_BE_DATE =
		"ERR_DATE_OF_BIRTH_MUST_BE_DATE";
	static readonly ERR_DATE_OF_BIRTH_REQUIRED = "ERR_DATE_OF_BIRTH_REQUIRED";

	static readonly ERR_ADDRESS_MUST_BE_STRING = "ERR_ADDRESS_MUST_BE_STRING";
	static readonly ERR_ADDRESS_REQUIRED = "ERR_ADDRESS_REQUIRED";

	static readonly ERR_BIO_MUST_BE_STRING = "ERR_BIO_MUST_BE_STRING";
	static readonly ERR_BIO_REQUIRED = "ERR_BIO_REQUIRED";
}
