export abstract class QueryFilterValidationMessage {
	static readonly ERR_SORT_FILTER_INVALID = "ERR_SORT_FILTER_INVALID";

	static readonly ERR_ORDER_INVALID = "ERR_ORDER_INVALID";

	static readonly ERR_PAGE_MUST_BE_INT = "ERR_PAGE_MUST_BE_INT";
	static readonly ERR_PAGE_INVALID = "ERR_PAGE_INVALID";

	static readonly ERR_LIMIT_MUST_BE_INT = "ERR_LIMIT_MUST_BE_INT";
	static readonly ERR_LIMIT_INVALID = "ERR_LIMIT_INVALID";
	static readonly ERR_LIMIT_MAX_100 = "ERR_LIMIT_MAX_100";

	static readonly ERR_STATUS_FILTER_INVALID = "ERR_STATUS_FILTER_INVALID";

	static readonly ERR_TYPE_FILTER_INVALID = "ERR_TYPE_FILTER_INVALID";

	static readonly ERR_DATE_FILTER_INVALID = "ERR_DATE_FILTER_INVALID";
	static readonly ERR_DATE_FILTER_MUST_BE_DATE = "ERR_DATE_FILTER_MUST_BE_DATE";
	static readonly ERR_DATE_START_FILTER_INVALID =
		"ERR_DATE_START_FILTER_INVALID";
	static readonly ERR_DATE_START_FILTER_MUST_BE_DATE =
		"ERR_DATE_START_FILTER_MUST_BE_DATE";
	static readonly ERR_DATE_END_FILTER_INVALID = "ERR_DATE_END_FILTER_INVALID";
	static readonly ERR_DATE_END_FILTER_MUST_BE_DATE =
		"ERR_DATE_END_FILTER_MUST_BE_DATE";
}
