export abstract class QueryFilterValidationMessage {
	static readonly ERR_SORT_FILTER_INVALID = "ERR_SORT_FILTER_INVALID";

	static readonly ERR_ORDER_INVALID = "ERR_ORDER_INVALID";

	static readonly ERR_PAGE_MUST_BE_INT = "ERR_PAGE_MUST_BE_INT";
	static readonly ERR_PAGE_INVALID = "ERR_PAGE_INVALID";

	static readonly ERR_LIMIT_MUST_BE_INT = "ERR_LIMIT_MUST_BE_INT";
	static readonly ERR_LIMIT_INVALID = "ERR_LIMIT_INVALID";
	static readonly ERR_LIMIT_MAX_100 = "ERR_LIMIT_MAX_100";

	static readonly ERR_STATUS_FILTER_INVALID = "ERR_STATUS_FILTER_INVALID";

	static readonly ERR_TYPE_FILTER_INVALID = "ERR_TYPE_FILTER_INVALID";

	static readonly ERR_DATE_FILTER_INVALID = "ERR_DATE_FILTER_INVALID";
	static readonly ERR_DATE_FILTER_MUST_BE_DATE = "ERR_DATE_FILTER_MUST_BE_DATE";
	static readonly ERR_DATE_START_FILTER_INVALID =
		"ERR_DATE_START_FILTER_INVALID";
	static readonly ERR_DATE_START_FILTER_MUST_BE_DATE =
		"ERR_DATE_START_FILTER_MUST_BE_DATE";
	static readonly ERR_DATE_END_FILTER_INVALID = "ERR_DATE_END_FILTER_INVALID";
	static readonly ERR_DATE_END_FILTER_MUST_BE_DATE =
		"ERR_DATE_END_FILTER_MUST_BE_DATE";

	static readonly ERR_ACCOUNT_BOOLEAN_FILTER_INVALID =
		"ERR_ACCOUNT_BOOLEAN_FILTER_INVALID";
	static readonly ERR_ACCOUNT_BOOLEAN_FILTER_MUST_BE_BOOLEAN =
		"ERR_ACCOUNT_BOOLEAN_FILTER_MUST_BE_BOOLEAN";
	static readonly ERR_CONSULTATION_META_BOOLEAN_FILTER_INVALID =
		"ERR_CONSULTATION_META_BOOLEAN_FILTER_INVALID";
	static readonly ERR_CONSULTATION_META_BOOLEAN_FILTER_MUST_BE_BOOLEAN =
		"ERR_CONSULTATION_META_BOOLEAN_FILTER_MUST_BE_BOOLEAN";
	static readonly ERR_OCCUPATION_BOOLEAN_FILTER_INVALID =
		"ERR_OCCUPATION_BOOLEAN_FILTER_INVALID";
	static readonly ERR_OCCUPATION_BOOLEAN_FILTER_MUST_BE_BOOLEAN =
		"ERR_OCCUPATION_BOOLEAN_FILTER_MUST_BE_BOOLEAN";
	static readonly ERR_PROFILE_BOOLEAN_FILTER_INVALID =
		"ERR_PROFILE_BOOLEAN_FILTER_INVALID";
	static readonly ERR_PROFILE_BOOLEAN_FILTER_MUST_BE_BOOLEAN =
		"ERR_PROFILE_BOOLEAN_FILTER_MUST_BE_BOOLEAN";
	static readonly ERR_CERTIFICATE_BOOLEAN_FILTER_INVALID =
		"ERR_CERTIFICATE_BOOLEAN_FILTER_INVALID";
	static readonly ERR_CERTIFICATE_BOOLEAN_FILTER_MUST_BE_BOOLEAN =
		"ERR_CERTIFICATE_BOOLEAN_FILTER_MUST_BE_BOOLEAN";
	static readonly ERR_SCHEDULE_BOOLEAN_FILTER_INVALID =
		"ERR_SCHEDULE_BOOLEAN_FILTER_INVALID";
	static readonly ERR_SCHEDULE_BOOLEAN_FILTER_MUST_BE_BOOLEAN =
		"ERR_SCHEDULE_BOOLEAN_FILTER_MUST_BE_BOOLEAN";
	static readonly ERR_EXCLUDE_SELF_BOOLEAN_FILTER_INVALID =
		"ERR_EXCLUDE_SELF_BOOLEAN_FILTER_INVALID";
	static readonly ERR_EXCLUDE_SELF_BOOLEAN_FILTER_MUST_BE_BOOLEAN =
		"ERR_EXCLUDE_SELF_BOOLEAN_FILTER_MUST_BE_BOOLEAN";
	static readonly ERR_REGISTERED_BOOLEAN_FILTER_INVALID =
		"ERR_REGISTERED_BOOLEAN_FILTER_INVALID";
	static readonly ERR_REGISTERED_BOOLEAN_FILTER_MUST_BE_BOOLEAN =
		"ERR_REGISTERED_BOOLEAN_FILTER_MUST_BE_BOOLEAN";

	static readonly ERR_CONSULTATION_TYPE_FILTER_INVALID =
		"ERR_CONSULTATION_TYPE_FILTER_INVALID";
	static readonly ERR_CONSULTATION_TYPE_FILTER_MUST_BE_ENUM =
		"ERR_CONSULTATION_TYPE_FILTER_MUST_BE_ENUM";
	static readonly ERR_MIN_PRICE_FILTER_INVALID = "ERR_MIN_PRICE_FILTER_INVALID";
	static readonly ERR_MIN_PRICE_FILTER_MUST_BE_NUMBER =
		"ERR_MIN_PRICE_FILTER_MUST_BE_NUMBER";
	static readonly ERR_MIN_PRICE_FILTER_MUST_BE_INT =
		"ERR_MIN_PRICE_FILTER_MUST_BE_INT";
	static readonly ERR_MAX_PRICE_FILTER_INVALID = "ERR_MAX_PRICE_FILTER_INVALID";
	static readonly ERR_MAX_PRICE_FILTER_MUST_BE_NUMBER =
		"ERR_MAX_PRICE_FILTER_MUST_BE_NUMBER";
	static readonly ERR_MAX_PRICE_FILTER_MUST_BE_INT =
		"ERR_MAX_PRICE_FILTER_MUST_BE_INT";
	static readonly ERR_MIN_EXPERIENCE_FILTER_INVALID =
		"ERR_MIN_EXPERIENCE_FILTER_INVALID";
	static readonly ERR_MIN_EXPERIENCE_FILTER_MUST_BE_INT =
		"ERR_MIN_EXPERIENCE_FILTER_MUST_BE_INT";
	static readonly ERR_MAX_EXPERIENCE_FILTER_INVALID =
		"ERR_MAX_EXPERIENCE_FILTER_INVALID";
	static readonly ERR_MAX_EXPERIENCE_FILTER_MUST_BE_INT =
		"ERR_MAX_EXPERIENCE_FILTER_MUST_BE_INT";
	static readonly ERR_DAY_OF_WEEK_FILTER_MUST_BE_ENUM =
		"ERR_DAY_OF_WEEK_FILTER_MUST_BE_ENUM";
}
