export abstract class RegistrationCertificateValidationMessage {
	static readonly REGISTRATION_NUMBER_REQUIRED = "REGISTRATION_NUMBER_REQUIRED";
	static readonly REGISTRATION_NUMBER_MUST_BE_STRING =
		"REGISTRATION_NUMBER_MUST_BE_STRING";
	static readonly REGISTRATION_NUMBER_INVALID = "REGISTRATION_NUMBER_INVALID";
	static readonly ISSUE_DATE_REQUIRED = "ISSUE_DATE_REQUIRED";
	static readonly ISSUE_DATE_MUST_BE_DATE = "ISSUE_DATE_MUST_BE_DATE";
	static readonly ISSUE_DATE_INVALID = "ISSUE_DATE_INVALID";
	static readonly VALID_UNTIL_REQUIRED = "VALID_UNTIL_REQUIRED";
	static readonly VALID_UNTIL_MUST_BE_DATE = "VALID_UNTIL_MUST_BE_DATE";
	static readonly VALID_UNTIL_INVALID = "VALID_UNTIL_INVALID";
}
