export abstract class RegistrationCertificateValidationMessage {
	static readonly ERR_REGISTRATION_NUMBER_REQUIRED =
		"ERR_REGISTRATION_NUMBER_REQUIRED";
	static readonly ERR_REGISTRATION_NUMBER_MUST_BE_STRING =
		"ERR_REGISTRATION_NUMBER_MUST_BE_STRING";
	static readonly ERR_REGISTRATION_NUMBER_INVALID =
		"ERR_REGISTRATION_NUMBER_INVALID";
	static readonly ERR_ISSUE_DATE_REQUIRED = "ERR_ISSUE_DATE_REQUIRED";
	static readonly ERR_ISSUE_DATE_MUST_BE_DATE = "ERR_ISSUE_DATE_MUST_BE_DATE";
	static readonly ERR_ISSUE_DATE_INVALID = "ERR_ISSUE_DATE_INVALID";
	static readonly ERR_VALID_UNTIL_REQUIRED = "ERR_VALID_UNTIL_REQUIRED";
	static readonly ERR_VALID_UNTIL_MUST_BE_DATE = "ERR_VALID_UNTIL_MUST_BE_DATE";
	static readonly ERR_VALID_UNTIL_INVALID = "ERR_VALID_UNTIL_INVALID";
}
