export abstract class RegistrationCertificateValidationMessage {
	static readonly REGISTRATION_NUMBER_NOT_BE_EMPTY =
		"REGISTRATION_NUMBER_NOT_BE_EMPTY";
	static readonly REGISTRATION_NUMBER_MUST_BE_A_STRING =
		"REGISTRATION_NUMBER_MUST_BE_A_STRING";
	static readonly REGISTRATION_NUMBER_MUST_BE_VALID =
		"REGISTRATION_NUMBER_MUST_BE_VALID";
	static readonly ISSUE_DATE_NOT_BE_EMPTY = "ISSUE_DATE_NOT_BE_EMPTY";
	static readonly ISSUE_DATE_MUST_BE_A_DATE = "ISSUE_DATE_MUST_BE_A_DATE";
	static readonly ISSUE_DATE_MUST_BE_VALID = "ISSUE_DATE_MUST_BE_VALID";
	static readonly VALID_UNTIL_NOT_BE_EMPTY = "VALID_UNTIL_NOT_BE_EMPTY";
	static readonly VALID_UNTIL_MUST_BE_A_DATE = "VALID_UNTIL_MUST_BE_A_DATE";
	static readonly VALID_UNTIL_MUST_BE_VALID = "VALID_UNTIL_MUST_BE_VALID";
}
