export abstract class TimeValidationMessage {
	static readonly ERR_TIME_REQUIRED = "ERR_TIME_REQUIRED";
	static readonly ERR_TIME_MUST_BE_DATE = "ERR_TIME_MUST_BE_DATE";
	static readonly ERR_TIME_MUST_BE_VALID = "ERR_TIME_MUST_BE_VALID";
	static readonly ERR_TIME_NOT_IN_RANGE = "ERR_TIME_NOT_IN_RANGE";

	static readonly ERR_START_TIME_REQUIRED = "ERR_START_TIME_REQUIRED";
	static readonly ERR_START_TIME_MUST_BE_DATE = "ERR_START_TIME_MUST_BE_DATE";
	static readonly ERR_START_TIME_MUST_BE_VALID = "ERR_START_TIME_MUST_BE_VALID";

	static readonly ERR_END_TIME_REQUIRED = "ERR_END_TIME_REQUIRED";
	static readonly ERR_END_TIME_MUST_BE_DATE = "ERR_END_TIME_MUST_BE_DATE";
	static readonly ERR_END_TIME_MUST_BE_VALID = "ERR_END_TIME_MUST_BE_VALID";

	static readonly ERR_TIME_RANGE_REQUIRED = "ERR_TIME_RANGE_REQUIRED";
	static readonly ERR_TIME_RANGE_MUST_BE_ARRAY = "ERR_TIME_RANGE_MUST_BE_ARRAY";
	static readonly ERR_TIME_RANGE_MUST_BE_VALID = "ERR_TIME_RANGE_MUST_BE_VALID";
	static readonly ERR_TIME_RANGE_OVERLAP = "ERR_TIME_RANGE_OVERLAP";

	static readonly ERR_MAX_TIME_RANGE = "ERR_MAX_TIME_RANGE_3";
}
