version: '3.2'
services:
  app-nutritionist:
    build:
      tags:
        - nutritalk-nutritionist:1.1.0-staging
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_NUTRITIONIST_PORT:?}:43702
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "yarn run db:migrate:prod && yarn run db:seed && yarn run start:prod"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME:?}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?}
      - POSTGRES_DB=${DB_NAME:?}
    env_file:
      - .env
    ports:
      - ${DB_PORT:?}:5432
    volumes:
      - nutritalk-postgres-data:/var/lib/postgresql/data

volumes:
  nutritalk-postgres-data:
