version: '3.8'
services:
  app-nutritionist:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_NUTRITIONIST_PORT:?}:43702
    depends_on:
      - db
      - cache-redis
    volumes:
      - .:/app
    command: sh -c "yarn run db:migrate:prod && yarn run start:prod"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME:?}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?}
      - POSTGRES_DB=${DB_NAME:?}
    ports:
      - 43711:${DB_PORT:?}
    env_file:
      - .env
    volumes:
      - nutritalk-postgres-data:/var/lib/postgresql/data

  cache-redis:
    image: redis:latest
    ports:
      - 43712:${REDIS_PORT:?}
    env_file:
      - .env
    command: redis-server
    volumes:
      - cache-data:/data

volumes:
  nutritalk-postgres-data:
  cache-data:
