// This file was auto-generated by prisma-generator-typescript-interfaces

export type AccountRoleEnum = "ADMIN" | "PATIENT" | "NUTRITIONIST";

export type GenderEnum = "MALE" | "FEMALE";

export type ConsultationTypeEnum = "ONLINE" | "OFFLINE";

export type TransactionStatusEnum =
	| "WAITING_PAYMENT"
	| "WAITING_CONFIRMATION"
	| "SCHEDULED"
	| "ON_PROCESS"
	| "FINISHED"
	| "RE_SCHEDULED"
	| "CANCELED";

export type OtpPurposeEnum =
	| "AUTH"
	| "AUTH_REGISTER"
	| "AUTH_FORGOT_PASSWORD"
	| "ACCOUNT"
	| "ACCOUNT_CHANGE_PASSWORD";

export type DayOfWeekEnum =
	| "MONDAY"
	| "TUESDAY"
	| "WEDNESDAY"
	| "THURSDAY"
	| "FRIDAY"
	| "SATURDAY"
	| "SUNDAY";

export type CreditActionEnum = "TOPUP" | "PAY_CONSULTATION" | "REFUND";

export type PatientActivityEnum =
	| "SEDENTARY"
	| "LIGHTLY_ACTIVE"
	| "MODERATELY_ACTIVE"
	| "VERY_ACTIVE"
	| "SUPER_ACTIVE";

export type DietPlanEnum = "WEIGHT_LOSS" | "WEIGHT_GAIN" | "MAINTAIN";

export type DietGoalEnum = "FAT_LOSS" | "MUSCLE_GAIN" | "MAINTAIN";

export type BmiStatusEnum =
	| "UNDERWEIGHT"
	| "NORMAL"
	| "OVERWEIGHT"
	| "OBESE"
	| "OBESE_II"
	| "OBESE_III";

export type NutritionistTypeEnum = "COUNSELOR" | "EXPERT";

export type PaymentSourceEnum = "CREDIT" | "MIDTRANS";

export interface IAccountEntity {
	id: string;
	email: string;
	password: string;
	refreshToken?: string | null;
	lastActivity?: Date | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	roleId?: string | null;
	patient?: IPatientEntity | null;
	nutritionist?: INutritionistEntity | null;
	sso?: ISingleSignOnEntity | null;
	role?: IRoleEntity | null;
	deviceInfo?: IDeviceInfoEntity | null;
}

export interface IProfileEntity {
	id: string;
	name: string;
	gender: GenderEnum;
	phoneNumber?: string | null;
	address?: string | null;
	placeOfBirth?: string | null;
	dateOfBirth?: Date | null;
	age?: number | null;
	imageKey?: string | null;
	bio?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	patient?: IPatientEntity | null;
	nutritionist?: INutritionistEntity | null;
}

export interface IAdminEntity {
	id: string;
	apiKey: string;
	createdAt?: Date | null;
	updatedAt?: Date | null;
}

export interface IOtpEntity {
	id: string;
	email: string;
	code: string;
	purpose: OtpPurposeEnum;
	expired: Date;
	createdAt?: Date | null;
	updatedAt?: Date | null;
}

export interface IWorkspaceServiceEntity {
	id: string;
	name: string;
	description: string;
	imageKey?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
}

export interface IBmiLimitEntity {
	id: string;
	status: BmiStatusEnum;
	min: number;
	max: number;
	createdAt?: Date | null;
	updatedAt?: Date | null;
}

export interface IFaqEntity {
	id: string;
	question: string;
	answer: string;
	createdAt?: Date | null;
	updatedAt?: Date | null;
}

export interface IPrivacyPolicyEntity {
	id: string;
	title: string;
	content: string;
	createdAt?: Date | null;
	updatedAt?: Date | null;
}

export interface ISignatureEntity {
	id: string;
	signature: string;
	createdAt?: Date | null;
	updatedAt?: Date | null;
}

export interface IConsultationEntity {
	id: string;
	trId?: string | null;
	status: TransactionStatusEnum;
	type: ConsultationTypeEnum;
	patientNote?: string | null;
	nutritionistNote?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	patient?: IPatientEntity | null;
	nutritionist?: INutritionistEntity | null;
	consultationTime?: IConsultationTimeEntity | null;
	transactionPrice?: ITransactionPriceEntity | null;
	transactionPayment?: ITransactionPaymentEntity | null;
	consultationReview?: IConsultationReviewEntity | null;
	medicalRecordHistory?: IMedicalRecordHistoryEntity | null;
	patientId?: string | null;
	nutritionistId?: string | null;
}

export interface IConsultationTimeEntity {
	id: string;
	start?: Date | null;
	end?: Date | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	consultation?: IConsultationEntity | null;
	consultationId?: string | null;
}

export interface ITransactionPriceEntity {
	id: string;
	sources: PaymentSourceEnum[];
	price: number;
	subTotal: number;
	credit: number;
	total: number;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	consultation?: IConsultationEntity | null;
	consultationId?: string | null;
}

export interface ITransactionPaymentEntity {
	id: string;
	method?: string | null;
	code?: string | null;
	status?: string | null;
	date?: Date | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	consultation?: IConsultationEntity | null;
	consultationId?: string | null;
}

export interface IConsultationReviewEntity {
	id: string;
	rating: number;
	description?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	consultation?: IConsultationEntity | null;
	consultationId?: string | null;
}

export interface ICreditEntity {
	id: string;
	balance: number;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	patient?: IPatientEntity | null;
	creditHistories?: ICreditHistoryEntity[];
	patientId?: string | null;
}

export interface ICreditHistoryEntity {
	id: string;
	action: CreditActionEnum;
	amount: number;
	note?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	credit?: ICreditEntity | null;
	creditId?: string | null;
}

export interface IDeviceInfoEntity {
	id: string;
	device?: string | null;
	fcmToken?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	accountId?: string | null;
	account?: IAccountEntity | null;
}

export interface IMedicalRecordKeyEntity {
	id: string;
	code?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	patient?: IPatientEntity | null;
	patientDetail?: IPatientDetailEntity | null;
	medicalRecordHistories?: IMedicalRecordHistoryEntity[];
}

export interface IPatientDetailEntity {
	id: string;
	name?: string | null;
	gender?: GenderEnum | null;
	dateOfBirth?: Date | null;
	age?: number | null;
	activityLevel?: PatientActivityEnum | null;
	dailyCalories?: number | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	medicalRecordKey?: IMedicalRecordKeyEntity | null;
	anthropometric?: IAnthropometricEntity | null;
	nutritionCarePlan?: INutritionCarePlanEntity | null;
	medicalRecordKeyId?: string | null;
	anthropometricId?: string | null;
	nutritionCarePlanId?: string | null;
}

export interface IMedicalRecordHistoryEntity {
	id: string;
	diagnosis?: string | null;
	notes?: string | null;
	others?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	medicalRecordKey?: IMedicalRecordKeyEntity | null;
	anthropometric?: IAnthropometricEntity | null;
	dietaryAssessment?: IDietaryAssessmentEntity | null;
	gastrointestinalRecord?: IGastrointestinalRecordEntity | null;
	consultation?: IConsultationEntity | null;
	medicalRecordKeyId?: string | null;
	anthropometricId?: string | null;
	dietaryAssessmentId?: string | null;
	gastrointestinalRecordId?: string | null;
	consultationId?: string | null;
}

export interface IAnthropometricEntity {
	id: string;
	height?: number | null;
	weight?: number | null;
	bmi?: number | null;
	bmiStatus?: BmiStatusEnum | null;
	fatPercentage?: number | null;
	muscleMass?: number | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	medicalRecordHistory?: IMedicalRecordHistoryEntity | null;
	patientDetail?: IPatientDetailEntity | null;
}

export interface IDietaryAssessmentEntity {
	id: string;
	usualDiet?: string | null;
	caloricIntake?: number | null;
	proteinIntake?: number | null;
	carbohydrateIntake?: number | null;
	fatIntake?: number | null;
	fiberIntake?: number | null;
	waterIntake?: number | null;
	foodAllergies?: string | null;
	supplements?: string | null;
	foodPreferences?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	medicalRecordHistory?: IMedicalRecordHistoryEntity | null;
}

export interface IGastrointestinalRecordEntity {
	id: string;
	disability?: string | null;
	allergies?: string | null;
	foodPreferences?: string | null;
	foodAvoidances?: string | null;
	appetite?: string | null;
	diarrhea?: boolean | null;
	constipation?: boolean | null;
	vomit?: boolean | null;
	nausea?: boolean | null;
	bloating?: boolean | null;
	swallowingDisorder?: boolean | null;
	chewingDisorder?: boolean | null;
	suckingDisorder?: boolean | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	medicalRecordHistory?: IMedicalRecordHistoryEntity | null;
}

export interface INutritionCarePlanEntity {
	id: string;
	dietPlan?: DietPlanEnum | null;
	dietGoal?: DietGoalEnum | null;
	dietPlanDescription?: string | null;
	exerciseGuidelines?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	patientDetail?: IPatientDetailEntity | null;
}

export interface INutritionistEntity {
	id: string;
	type?: NutritionistTypeEnum | null;
	nip?: string | null;
	nidn?: string | null;
	isAvailable?: boolean | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	account?: IAccountEntity | null;
	profile?: IProfileEntity | null;
	consultationMeta?: IConsultationMetaEntity | null;
	occupation?: IOccupationEntity | null;
	price?: IPriceEntity | null;
	registrationCertificate?: IRegistrationCertificateEntity | null;
	schedules?: IScheduleEntity[];
	consultations?: IConsultationEntity[];
	accountId?: string | null;
	profileId?: string | null;
}

export interface IConsultationMetaEntity {
	id: string;
	avgRating?: number | null;
	consultation?: number | null;
	successConsultation?: number | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	nutritionist?: INutritionistEntity | null;
	nutritionistId?: string | null;
}

export interface IRegistrationCertificateEntity {
	id: string;
	registrationNumber: string;
	issueDate?: Date | null;
	validUntil?: Date | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	nutritionist?: INutritionistEntity | null;
	nutritionistId?: string | null;
}

export interface IOccupationEntity {
	id: string;
	name: string;
	workPlace: string;
	experience: number;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	nutritionist?: INutritionistEntity | null;
	nutritionistId?: string | null;
}

export interface IPriceEntity {
	id: string;
	online: number;
	offline: number;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	nutritionist?: INutritionistEntity | null;
	nutritionistId?: string | null;
}

export interface IScheduleEntity {
	id: string;
	dayOfWeek: DayOfWeekEnum;
	dayOfWeekIndex: number;
	active: boolean;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	nutritionist?: INutritionistEntity | null;
	scheduleTimes?: IScheduleTimeEntity[];
	nutritionistId?: string | null;
}

export interface IScheduleTimeEntity {
	id: string;
	start: Date;
	end: Date;
	active: boolean;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	schedule?: IScheduleEntity | null;
	scheduleId?: string | null;
}

export interface IPatientEntity {
	id: string;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	account?: IAccountEntity | null;
	profile?: IProfileEntity | null;
	medicalRecordKey?: IMedicalRecordKeyEntity | null;
	credit?: ICreditEntity | null;
	consultations?: IConsultationEntity[];
	accountId?: string | null;
	profileId?: string | null;
	medicalRecordKeyId?: string | null;
}

export interface IBasePermissionEntity {
	id: string;
	key: string;
	description?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	rolePermissions?: IRolePermissionEntity[];
}

export interface IRoleEntity {
	id: string;
	accountRole: AccountRoleEnum;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	accountId?: string | null;
	permissions?: IRolePermissionEntity[];
	account?: IAccountEntity | null;
}

export interface IRolePermissionEntity {
	id: string;
	isPermitted: boolean;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	roleId?: string | null;
	role?: IRoleEntity | null;
	permission?: IBasePermissionEntity | null;
	basePermissionId?: string | null;
}

export interface ISingleSignOnEntity {
	id: string;
	googleSSO?: IGoogleSSOEntity | null;
	account?: IAccountEntity | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	accountId?: string | null;
}

export interface IGoogleSSOEntity {
	id: string;
	googleId: string;
	email: string;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	ssoId?: string | null;
	sso?: ISingleSignOnEntity | null;
}
