export abstract class AccountErrorMessage {
	static readonly ERR_ACCOUNT_NOT_FOUND = "ERR_ACCOUNT_NOT_FOUND";
	static readonly ERR_ACCOUNT_NOT_ADMIN = "ERR_ACCOUNT_NOT_ADMIN";
	static readonly ERR_ACCOUNT_NOT_PATIENT = "ERR_ACCOUNT_NOT_PATIENT";
	static readonly ERR_ACCOUNT_NOT_NUTRITIONIST = "ERR_ACCOUNT_NOT_NUTRITIONIST";
	static readonly ERR_ACCOUNT_ALREADY_EXIST = "ERR_ACCOUNT_ALREADY_EXIST";
	static readonly ERR_ACCOUNT_ALREADY_SIGN_OUT = "ERR_ACCOUNT_ALREADY_SIGN_OUT";
}
