export abstract class QueueKeyConstant {
	static readonly MAIL_QUEUE = "MAIL_QUEUE";
	static readonly MAIL_OTP_QUEUE_PROCESS = "MAIL_OTP_QUEUE_PROCESS";
	static readonly MAIL_QUEUE_PROCESSOR = "MAIL_QUEUE_PROCESSOR";

	static readonly DICE_BEAR_QUEUE = "DICE_BEAR_QUEUE";
	static readonly DICE_BEAR_QUEUE_PROCESS = "DICE_BEAR_QUEUE_PROCESS";
	static readonly DICE_BEAR_QUEUE_PROCESSOR = "DICE_BEAR_QUEUE_PROCESSOR";

	static readonly IMAGE_DOWNLOAD_QUEUE = "IMAGE_DOWNLOAD_QUEUE";
	static readonly IMAGE_DOWNLOAD_QUEUE_PROCESS = "IMAGE_DOWNLOAD_QUEUE_PROCESS";
	static readonly IMAGE_DOWNLOAD_QUEUE_PROCESSOR =
		"IMAGE_DOWNLOAD_QUEUE_PROCESSOR";
}
