export abstract class AccountErrorMessage {
	static readonly ERR_ACCOUNT_NOT_FOUND = "ERR_ACCOUNT_NOT_FOUND";
	static readonly ERR_ACCOUNT_NOT_ADMIN = "ERR_ACCOUNT_NOT_ADMIN";
	static readonly ERR_ACCOUNT_NOT_PATIENT = "ERR_ACCOUNT_NOT_PATIENT";
	static readonly ERR_ACCOUNT_NOT_NUTRITIONIST = "ERR_ACCOUNT_NOT_NUTRITIONIST";
	static readonly ERR_ACCOUNT_ALREADY_EXIST = "ERR_ACCOUNT_ALREADY_EXIST";
	static readonly ERR_ACCOUNT_ALREADY_SIGN_OUT = "ERR_ACCOUNT_ALREADY_SIGN_OUT";

	static readonly ERR_PASSWORD_NOT_MATCH = "ERR_PASSWORD_NOT_MATCH";

	static readonly ERR_OTP_EXPIRED = "ERR_OTP_EXPIRED";
	static readonly ERR_OTP_INVALID = "ERR_OTP_INVALID";

	static readonly ERR_SIGNATURE_INVALID = "ERR_SIGNATURE_INVALID";

	static readonly ERR_SSO = "ERR_SSO";
	static readonly ERR_SSO_NOT_FOUND = "ERR_SSO_NOT_FOUND";
	static readonly ERR_SSO_ALREADY_EXISTS = "ERR_SSO_ALREADY_EXISTS";

	static readonly ERR_SSO_GOOGLE = "ERR_SSO_GOOGLE";
	static readonly ERR_SSO_GOOGLE_NOT_FOUND = "ERR_SSO_GOOGLE_NOT_FOUND";
	static readonly ERR_SSO_GOOGLE_ALREADY_EXISTS =
		"ERR_SSO_GOOGLE_ALREADY_EXISTS";
	static readonly ERR_SSO_GOOGLE_ALREADY_TAKEN = "ERR_SSO_GOOGLE_ALREADY_TAKEN";

	static readonly ERR_FIREBASE_AUTHENTICATION = "ERR_FIREBASE_AUTHENTICATION";
	static readonly ERR_FIREBASE_AUTHENTICATION_INVALID =
		"ERR_FIREBASE_AUTHENTICATION_INVALID";
}
