export abstract class NutritionistErrorMessage {
	static readonly ERR_NUTRITIONIST_NOT_FOUND = "ERR_NUTRITIONIST_NOT_FOUND";

	static readonly ERR_CONSULTATION_META_NOT_FOUND =
		"ERR_CONSULTATION_META_NOT_FOUND";

	static readonly OCCUPATION_NOT_FOUND = "OCCUPATION_NOT_FOUND";
	static readonly OCCUPATION_ALREADY_EXISTS = "OCCUPATION_ALREADY_EXISTS";

	static readonly ERR_PRICE_NOT_FOUND = "ERR_PRICE_NOT_FOUND";

	static readonly ERR_CERTIFICATE_NOT_FOUND = "ERR_CERTIFICATE_NOT_FOUND";
	static readonly ERR_CERTIFICATE_ALREADY_EXISTS =
		"ERR_CERTIFICATE_ALREADY_EXISTS";

	static readonly ERR_SCHEDULE_NOT_FOUND = "ERR_SCHEDULE_NOT_FOUND";
	static readonly ERR_SCHEDULE_TIME_NOT_FOUND = "ERR_SCHEDULE_TIME_NOT_FOUND";
	static readonly ERR_SCHEDULE_TIME_OVERLAP = "ERR_SCHEDULE_TIME_OVERLAP";
	static readonly ERR_MAX_SCHEDULE_TIME_3 = "ERR_MAX_SCHEDULE_TIME_3";

	static readonly ERR_NUTRITIONIST_SYSTEM_SETTING_NOT_FOUND =
		"ERR_NUTRITIONIST_SYSTEM_SETTING_NOT_FOUND";
}
