export abstract class PasswordValidationMessage {
  static readonly ERR_PASSWORD_REQUIRED = 'ERR_PASSWORD_REQUIRED';
  static readonly ERR_PASSWORD_MUST_BE_STRING = 'ERR_PASSWORD_MUST_BE_STRING';
  static readonly ERR_PASSWORD_MIN_LENGTH = 'ERR_PASSWORD_MIN_LENGTH';
  static readonly ERR_PASSWORD_MAX_LENGTH = 'ERR_PASSWORD_MAX_LENGTH';
  static readonly ERR_PASSWORD_PATTERN = 'ERR_PASSWORD_PATTERN';
}
