# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI Build Dev

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  HUSKY: 0

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: |
          touch ./.credentials/${{secrets.FIREBASE_JSON_NAME}}.json
          echo "${{secrets.FIREBASE_JSON}}" | base64 --decode >> ./.credentials/${{secrets.FIREBASE_JSON_NAME}}.json

      - run: |
          touch .env 
          echo "${{secrets.WORKFLOW_ENV}}" | base64 --decode >> .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nutritalk-base:dev
