name: Node.js Deploy Staging

on:
  pull_request:
    types: [closed]
    branches: ["staging"]

env:
  HUSKY: 0

jobs:
  build:
    if: github.event.pull_request.merged == true
    environment: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          touch ./.credentials/${{secrets.FIREBASE_JSON_NAME}}.json
          echo "${{secrets.FIREBASE_JSON}}" | base64 --decode >> ./.credentials/${{secrets.FIREBASE_JSON_NAME}}.json

      - run: |
          touch .env 
          echo "${{secrets.WORKFLOW_ENV}}" >> .env
          cat .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nutritalk-base:staging

  deploy:
    if: github.event.pull_request.merged == true
    needs: build
    environment: CD
    runs-on: ubuntu-latest
    steps:
      - name: Initialize ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_API_TOKEN }}

      - name: Deploy to staging remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/nutritalk-be
            git checkout staging
            git pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nutritalk-base:staging
            docker-compose down -v 
            docker-compose up -d --build --force-recreate

  post-deploy:
    if: github.event.pull_request.merged == true
    needs: deploy
    environment: CD
    runs-on: ubuntu-latest
    steps:
      - name: Initialize ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_API_TOKEN }}

      - name: Post deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            docker image prune -a -f
            docker builder prune -a -f
