name: Node.js Deploy Staging

on:
  pull_request:
    types: [closed]
    branches: ["staging"]

env:
  HUSKY: 0

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: |
          touch .env 
          echo "${{secrets.WORKFLOW_ENV}}" >> .env
          cat .env
      - run: yarn install --immutable --frozen-lockfile
      - run: yarn run db:generate
      - run: yarn run lint
      - run: yarn run build

  deploy:
    if: github.event.pull_request.merged == true
    environment: CD
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.ACTION_SECRET }}
          port: 22
          script: |
            cd ~/nutritalk-be
            git checkout staging
            git pull
