name: Node.js Deploy Staging

on:
  pull_request:
    types: [closed]
    branches: ["staging"]

env:
  HUSKY: 0

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    environment: CD
    runs-on: ubuntu-latest
    steps:
      - name: Initialize ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_API_TOKEN }}

      - name: Deploy to staging remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/nutritalk-be-staging
            git checkout staging
            git pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nutritalk-base:staging
            docker-compose -f docker-compose.staging.yml down -v
            echo "${{secrets.CD_ENV_STAGING}}" | base64 --decode > .env
            docker-compose -f docker-compose.staging.yml up -d --build --force-recreate

  post-deploy:
    if: github.event.pull_request.merged == true
    needs: deploy
    environment: CD
    runs-on: ubuntu-latest
    steps:
      - name: Initialize ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_API_TOKEN }}

      - name: Post deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            docker image prune -a -f
            docker builder prune -a -f
